package main

//go:generate go-bindata -pkg files_assets -o apps/files/assets.go apps/files/css/... apps/files/js/... apps/files/img/...

//go:generate go-bindata -pkg federatedfilesharing -o apps/federatedfilesharing/assets.go apps/federatedfilesharing/css/... apps/federatedfilesharing/js/... apps/federatedfilesharing/img/...

//go:generate go-bindata -pkg files_sharing -o apps/files_sharing/assets.go apps/files_sharing/css/... apps/files_sharing/js/... apps/files_sharing/img/...

//go:generate go-bindata -pkg files_trashbin -o apps/files_trashbin/assets.go apps/files_trashbin/css/... apps/files_trashbin/img/... apps/files_trashbin/js/...

//go:generate go-bindata -pkg files_videoplayer -o apps/files_videoplayer/assets.go apps/files_videoplayer/...

//go:generate go-bindata -pkg core -o core/assets.go core/css/... core/js/... core/img/... core/fonts/... core/search/... core/vendor/...

//go:generate go-bindata -pkg settings -o settings/assets.go settings/css/... settings/img/... settings/js/...

//go:generate go-bindata -pkg main -o index.go index.html
